# Generated by Django 4.2.30 on 2026-04-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="servergroup",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="servergroup",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_groups",
                to="core.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="servergroup",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="core_servergroup_project_name_uniq",
            ),
        ),
    ]
