# Generated by Django 4.2.30 on 2026-04-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_alter_servergroup_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_assignments', to='core.member'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.team'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('member__isnull', True), ('team__isnull', False)), models.Q(('member__isnull', False), ('team__isnull', True)), _connector='OR'), name='assignment_team_xor_member'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'server_group'), name='assignment_unique_team_server_group'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('member', 'server_group'), name='assignment_unique_member_server_group'),
        ),
    ]
