# Generated by Django 4.2.30 on 2026-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignment_team_or_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_revoked',
            field=models.BooleanField(db_index=True, default=False, help_text='Globally revoked: removed from all teams; direct assignments set to removed for convergence.'),
        ),
    ]
