# Generated by Django 4.2.30 on 2026-05-11 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workspaceadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat_logs', to='core.server')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['server', 'recorded_at'], name='core_server_server__057f6d_idx')],
            },
        ),
    ]
