import shlex

from django.db.models import Q

from .linux_groups import BLOCKED_SUPPLEMENTAL_GROUPS
from .models import Assignment


def _effective_role(prev_role, new_role):
    if prev_role is None:
        return new_role
    if "sudo" in (prev_role, new_role):
        return "sudo"
    if "user" in (prev_role, new_role):
        return "user"
    return "removed"


def _bash_blocked_group_case_lines():
    names = sorted(BLOCKED_SUPPLEMENTAL_GROUPS)
    return "|".join(shlex.quote(n) for n in names)


def generate_provision_script(server_group, request=None):
    """Generate an idempotent bash provisioning script for a server group."""

    assignments = (
        Assignment.objects.filter(server_group=server_group)
        .filter(Q(team__isnull=False) | Q(member__isnull=False))
        .select_related("team", "member")
        .prefetch_related("team__members__ssh_keys")
    )

    member_roles = {}

    for assignment in assignments:
        if assignment.team_id:
            for member in assignment.team.members.all():
                keys = list(member.ssh_keys.all())
                if member.id in member_roles:
                    prev_role = member_roles[member.id][1]
                    eff = _effective_role(prev_role, assignment.role)
                    member_roles[member.id] = (member, eff, keys)
                else:
                    member_roles[member.id] = (member, assignment.role, keys)
        else:
            member = assignment.member
            keys = list(member.ssh_keys.all())
            if member.id in member_roles:
                prev_role = member_roles[member.id][1]
                eff = _effective_role(prev_role, assignment.role)
                member_roles[member.id] = (member, eff, keys)
            else:
                member_roles[member.id] = (member, assignment.role, keys)

    supplemental_groups = list(server_group.supplemental_groups or [])
    blocked_case = _bash_blocked_group_case_lines()

    base_url = ""
    if request:
        base_url = request.build_absolute_uri("/").rstrip("/")

    token = str(server_group.provision_token)

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Sanctum Provisioning Script",
        f"# Server Group: {server_group.name}",
        "# This script is idempotent -- safe to run via cron.",
        "",
        'LOG="/var/log/sanctum.log"',
        'MARKER="# MANAGED BY SANCTUM"',
        'LEGACY_MARKERS=("# Generated by userify")',
        "",
        'log() { echo "$(date -Is) SANCTUM: $*" >> "$LOG"; }',
        "",
        "is_blocked_group() {",
        "  case \"$1\" in",
        f"    {blocked_case})",
        "      return 0",
        "      ;;",
        "    *)",
        "      return 1",
        "      ;;",
        "  esac",
        "}",
        "",
        "ensure_supplemental_groups() {",
        '  local username="$1"; shift',
        '  local desired_groups=("$@")',
        "",
        '  for group_name in "${desired_groups[@]}"; do',
        '    if is_blocked_group "$group_name"; then',
        '      log "BLOCK privileged supplemental group $group_name for $username"',
        "      continue",
        "    fi",
        "",
        '    if ! getent group "$group_name" >/dev/null; then',
        '      log "SKIP unknown supplemental group $group_name for $username"',
        "      continue",
        "    fi",
        "",
        '    if ! id -nG "$username" | grep -qw "$group_name"; then',
        '      usermod -aG "$group_name" "$username"',
        '      log "GROUP+ $username $group_name"',
        "    else",
        '      log "OK group $username already in $group_name"',
        "    fi",
        "  done",
        "}",
        "",
        "remove_supplemental_groups() {",
        '  local username="$1"; shift',
        '  local managed_groups=("$@")',
        "",
        '  for group_name in "${managed_groups[@]}"; do',
        '    if is_blocked_group "$group_name"; then',
        '      log "SKIP removal for blocked group $group_name for $username"',
        "      continue",
        "    fi",
        "",
        '    if ! getent group "$group_name" >/dev/null; then',
        '      log "SKIP missing supplemental group $group_name for $username"',
        "      continue",
        "    fi",
        "",
        '    if id -nG "$username" | grep -qw "$group_name"; then',
        '      gpasswd -d "$username" "$group_name" >/dev/null 2>&1 || true',
        '      log "GROUP- $username $group_name"',
        "    fi",
        "  done",
        "}",
        "",
        "SANCTUM_LINUX_NAME_MAX=32",
        "",
        "sanctum_logical_username() {",
        '  local u="$1"',
        '  case "$u" in',
        '    revoked:*|deleted:*) echo "${u#*:}" ;;',
        '    *) echo "$u" ;;',
        "  esac",
        "}",
        "",
        "sanctum_rename_target() {",
        '  local prefix="$1" username="$2"',
        '  local target="${prefix}:${username}"',
        '  if [ "${#target}" -gt "$SANCTUM_LINUX_NAME_MAX" ]; then',
        '    log "SKIP rename ${username}: target ${target} exceeds ${SANCTUM_LINUX_NAME_MAX} chars"',
        "    return 1",
        "  fi",
        '  printf "%s" "$target"',
        "}",
        "",
        "strip_sanctum_access() {",
        '  local username="$1"',
        '  id "$username" &>/dev/null || return 0',
        '  usermod -L "$username" 2>/dev/null || true',
        "  local home",
        '  home=$(eval echo "~$username")',
        '  rm -f "$home/.ssh/authorized_keys"',
        '  gpasswd -d "$username" sudo 2>/dev/null || true',
        '  remove_supplemental_groups "$username" "${MANAGED_SUPPLEMENTAL_GROUPS[@]}"',
        "}",
        "",
        "rename_sanctum_account() {",
        '  local from="$1" to="$2"',
        '  if [ "$from" = "$to" ]; then',
        "    return 0",
        "  fi",
        '  if ! id "$from" &>/dev/null; then',
        "    return 1",
        "  fi",
        '  if id "$to" &>/dev/null; then',
        '    log "SKIP rename $from -> $to: target already exists"',
        "    return 1",
        "  fi",
        '  if ! usermod -l "$to" "$from"; then',
        '    log "RENAME_FAILED $from -> $to"',
        "    return 1",
        "  fi",
        '  usermod -d "/home/$to" -m "$to" 2>/dev/null || true',
        '  log "RENAMED $from -> $to"',
        "  return 0",
        "}",
        "",
        "reactivate_sanctum_user() {",
        '  local username="$1"',
        '  local alt=""',
        '  for prefix in revoked deleted; do',
        '    alt="${prefix}:${username}"',
        '    if id "$alt" &>/dev/null; then',
        '      rename_sanctum_account "$alt" "$username" || return 1',
        '      usermod -U "$username" 2>/dev/null || true',
        '      log "REACTIVATED $alt -> $username"',
        "      return 0",
        "    fi",
        "  done",
        "  return 1",
        "}",
        "",
        "revoke_user() {",
        '  local username="$1"',
        '  local target=""',
        '  target=$(sanctum_rename_target revoked "$username") || { strip_sanctum_access "$username"; return; }',
        '  if id "$target" &>/dev/null; then',
        '    strip_sanctum_access "$target"',
        '    log "OK already revoked $username as $target"',
        "    return",
        "  fi",
        '  if id "$username" &>/dev/null; then',
        '    strip_sanctum_access "$username"',
        '    rename_sanctum_account "$username" "$target" || true',
        "    return",
        "  fi",
        '  if id "deleted:${username}" &>/dev/null; then',
        '    log "SKIP revoke $username: already deleted: account exists"',
        "  fi",
        "}",
        "",
        "delete_user() {",
        '  local username="$1"',
        '  local target=""',
        '  target=$(sanctum_rename_target deleted "$username") || {',
        '    for current in "$username" "revoked:${username}" "deleted:${username}"; do',
        '      strip_sanctum_access "$current"',
        "    done",
        "    return",
        "  fi",
        '  if id "$target" &>/dev/null; then',
        '    strip_sanctum_access "$target"',
        '    log "OK already deleted $username as $target"',
        "    return",
        "  fi",
        '  for current in "$username" "revoked:${username}"; do',
        '    if id "$current" &>/dev/null; then',
        '      strip_sanctum_access "$current"',
        '      rename_sanctum_account "$current" "$target" && return',
        "    fi",
        "  done",
        "}",
        "",
        "ensure_user() {",
        '  local username="$1" role="$2"',
        "  shift 2",
        '  local keys=("$@")',
        "",
        '  reactivate_sanctum_user "$username" || true',
        "",
        '  if ! id "$username" &>/dev/null; then',
        '    useradd -m -s /bin/bash "$username"',
        '    log "CREATED user $username"',
        "  fi",
        "",
        "  local home",
        '  home=$(eval echo "~$username")',
        '  mkdir -p "$home/.ssh"',
        "",
        "  {",
        '    echo "$MARKER"',
        '    for key in "${keys[@]}"; do',
        '      echo "$key"',
        "    done",
        '  } > "$home/.ssh/authorized_keys"',
        "",
        '  chown -R "$username:$username" "$home/.ssh"',
        '  chmod 700 "$home/.ssh"',
        '  chmod 600 "$home/.ssh/authorized_keys"',
        "",
        '  if [ "$role" = "sudo" ]; then',
        '    if ! groups "$username" 2>/dev/null | grep -qw sudo; then',
        '      usermod -aG sudo "$username"',
        '      log "SUDO+ $username"',
        "    fi",
        "  else",
        '    if groups "$username" 2>/dev/null | grep -qw sudo; then',
        '      gpasswd -d "$username" sudo 2>/dev/null || true',
        '      log "SUDO- $username"',
        "    fi",
        "  fi",
        "",
        '  usermod -U "$username" 2>/dev/null || true',
        "",
        '  ensure_supplemental_groups "$username" "${MANAGED_SUPPLEMENTAL_GROUPS[@]}"',
        "}",
        "",
        "# --- Managed supplemental groups (Sanctum-owned) ---",
        "MANAGED_SUPPLEMENTAL_GROUPS=(",
    ]

    if supplemental_groups:
        for g in supplemental_groups:
            lines.append(f"  {shlex.quote(g)}")
    lines.append(")")
    lines.extend(["", "# --- Desired State ---", ""])

    for _mid, (member, role, keys) in sorted(
        member_roles.items(), key=lambda x: x[1][0].username
    ):
        if role in ("user", "sudo"):
            key_args = [
                shlex.quote(k.public_key.strip()) for k in keys if k.public_key.strip()
            ]
            if not key_args:
                lines.append(
                    f"# SKIPPED {member.username}: no SSH keys configured"
                )
                continue
            lines.append(
                f"ensure_user {shlex.quote(member.username)} {shlex.quote(role)} \\"
            )
            for i, ka in enumerate(key_args):
                suffix = " \\" if i < len(key_args) - 1 else ""
                lines.append(f"  {ka}{suffix}")
            lines.append("")
        elif role == "removed":
            lines.append(f"revoke_user {shlex.quote(member.username)}")
            lines.append("")

    known_usernames = sorted(
        {member.username for _mid, (member, _role, _keys) in member_roles.items()}
    )
    known_str = "|".join([""] + known_usernames + [""])

    lines.extend([
        "# --- Cleanup: lock stale managed users no longer in desired state ---",
        f'KNOWN_USERS="{known_str}"',
        "",
        "is_managed() {",
        '  local ak="$1"',
        '  grep -q "$MARKER" "$ak" && return 0',
        '  for lm in "${LEGACY_MARKERS[@]}"; do',
        '    grep -q "$lm" "$ak" && return 0',
        "  done",
        "  return 1",
        "}",
        "",
        "for home_dir in /home/*/; do",
        '  [ -d "$home_dir" ] || continue',
        '  username=$(basename "$home_dir")',
        '  logical=$(sanctum_logical_username "$username")',
        '  ak="$home_dir/.ssh/authorized_keys"',
        '  [ -f "$ak" ] || continue',
        '  is_managed "$ak" || continue',
        '  case "$KNOWN_USERS" in',
        '    *"|$logical|"*) ;;',
        '    *) delete_user "$logical" ;;',
        "  esac",
        "done",
        "",
    ])

    if base_url:
        lines.extend([
            "# --- Heartbeat ---",
            f"curl -sSL -X POST {shlex.quote(base_url + '/api/heartbeat/' + token + '/')} \\",
            '  -d "hostname=$(hostname)" &>/dev/null || true',
        ])

    lines.append("")
    return "\n".join(lines)
